export const HIDE_HEADER = 'HIDE_HEADER';
export const NOT_HIDE_HEADER = 'NOT_HIDE_HEADER';
export const SET_ROLE = "SET_ROLE";
export const CHOICE_PLACE = "CHOICE_PLACE";
export const SET_LIST_HASHTAG = 'SET_LIST_HASHTAG';
export const CHANGE_HASHTAG = 'CHANGE_HASHTAG';